### PR TITLE
governance: add voting support for snapshot.org

### PR DESCRIPTION
**Pull request by MaxMustermann2**

### CODE REVIEW

**Comment by MaxMustermann2** [comment]
A couple of tests

#### Using snapshot's official example as per https://docs.snapshot.org/snapshot.js#cast-a-vote
```bash
$ ./hmy governance vote-proposal --space yam.eth --proposal 0x21ea31e896ec5b5a49a3653e51e787ee834aaf953263144ab936ed756f36609f --proposal-type single-choice --choice 1 --app my-app --key system-imported
commit: v454-v1.2.9-4-gab83408, error: error: unauthorized, not in voting window
check hmy cookbook for valid examples or try adding a `--help` flag
```

#### A random active proposal
```bash
$ ./hmy governance vote-proposal --space gitcoindao.eth --proposal 0x64bc572f0b50346e8d1f300b39d02204750ec4308002794dac9247422adb27bd --proposal-type single-choice --choice 1 --app my-app --key system-imported
commit: v454-v1.2.9-4-gab83408, error: error: unauthorized, no voting power
check hmy cookbook for valid examples or try adding a `--help` flag
```

**Review by rlan35 — APPROVED** [review]

**Comment by rlan35** [comment]
@Chainode please review this PR too.

**Review by LuttyYang — APPROVED** [review]

**Comment by rlan35** [comment]
Looks good. Feel free to merge after the real governance test on testnet.

**Comment by Chainode** [comment]
We have checked and it looks ok. We definitely recommend to test this on Testnet before releasing on Mainnet. During the Testnet tests, it would be relevant to analyze which information is sent exactly by the machine that operates/executes a governance. The main motivation is to be sure no sensible and unwanted information that could impact security is sent through this process.

**Comment by MaxMustermann2** [comment]
The following instructions were provided by Snapshot Labs on snapshot-labs/snapshot-strategies#803 and applied by @jacksteroo on the `harmony-testnet.eth` space.
 - Remove `eth-balance` strategy
 - Change network to Harmony Mainnet
 - Click on the `harmony-staking` strategy and change the network to Harmony Mainnet
 
After these instructions were all applied, I [created a new proposal](https://snapshot.org/#/harmony-testnet.eth/proposal/0x3f05efe88ea3b3f5ca08142eacc56e50fc5bd387d6fc87087434d56caf2e02e7) on which I voted using the `hmy` CLI.
```bash
$ ./hmy governance vote-proposal --space harmony-testnet.eth --proposal 0x3f05efe88ea3b3f5ca08142eacc56e50fc5bd387d6fc87087434d56caf2e02e7 --proposal-type single-choice --choice 1 --key fiction-imported
{
  "id": "0xc4c4d7385780f2ffafb4d2852b68f1491d2987494d6737af039ddc4b893daa42",
  "ipfs": "bafkreiash2neegu5ja6cpakb6ipqnsvizabvkzdkyw2nsyraf5c33n4bhq",
  "relayer": {
    "address": "0x8BBE4Ac64246d600BC2889ef5d83809D138F03DF",
    "receipt": "0xe75ad47d3365ca2a7f96e2f6e0c331a9557f907630d7f6952cf98ea601151a950817e2ff24f4690291c93d525420989cc8da6a44f11cc5862c388b6e0af39de41c"
  }
}
``` 

The PR can now be merged.

**Pull request merged**
